server:
  port: 8087

spring:
  application:
    name: CONFIGSERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Shailesh-sal786/configserver
          clone-on-start: true

